### ISSUE TITLE
Support other chromium based browsers

### ISSUE THREAD

**Issue by thewh1teagle** [xaitax/Chrome-App-Bound-Encryption-Decryption#1]
Does it works on Brave / Edge? 
It's interesting that it doesn't requires admin rights. saw other POCs but all of them required calling system/user DPAPI.

**Comment by xaitax** [comment]
> Does it works on Brave / Edge?

It should but haven't looked at them. Since Brave has it's code (or most?) public, it shouldn't be too hard to adjust. Edge I don't know.

> It's interesting that it doesn't requires admin rights. saw other POCs but all of them required calling system/user DPAPI.

The tool itself doesn't and can be run from regular user privileges. Getting past the path validation and placing the binary in the directory can be achieved with e.g. fodhelper UAC bypass.

**Comment by xaitax** [comment]
Hi @thewh1teagle 

Brave works as well by adjusting the `CLSID_Elevator` & `IID_IElevator `accordingly.

![image](https://github.com/user-attachments/assets/c4fed278-67ac-4e41-8749-b10550b8d1a2)

Will push an update soon.

**Comment by xaitax** [comment]
f67cfc4925929503ca5623ed150604ac8f58a52a should support Edge & Brave now.
